trigger:
- main

pool:
  name: 'Default'

stages:
- stage: RunAnsible
  jobs: 
  - job: RunPlaybookOnHosts
    steps:
    - script: |
        echo "Running Ansible playbook..."

        
        echo $(SSH_PASSWORD)
        echo $(SSH_PASSWORD)
        echo $(SSH_PASSWORD)
        echo $(SSH_PASSWORD)
        echo $(SSH_PASSWORD)
        echo $(SSH_PASSWORD)
        echo $(SSH_PASSWORD)
        echo $(SSH_PASSWORD)
        echo $(SSH_PASSWORD)
        echo $(SSH_PASSWORD)
        echo $(SSH_PASSWORD)
        echo $(SSH_PASSWORD)
        
        
        export ANSIBLE_HOST_KEY_CHECKING=False
        ansible-playbook /home/kdsouza/Project/playbook-test.yml -vvvv
        -e "ansible_ssh_pass=$(SSH_PASSWORD)"
      env: 
        SSH_PASSWORD: $(SSH_PASSWORD)
      displayName: Run Ansible Playbook with sshpass
