trigger:
- main

pool:
  name: 'Default'

variables:
  - name: ssh_password
    value: $(SSH_PASSWORD)

stages:
- stage: RunAnsible
  jobs: 
  - job: RunPlaybookOnHosts
    steps:
    - script: |
        echo "Creating Ansible Vault File"

        # Write secret to YAML in-memory using env var
        echo "my_key: $SSH_PASSWORD" > secret.yml

        # Encrypt with Ansible Vault
        ansible-vault encrypt secret.yml --vault-password-file vault_pass.txt

        echo "Running Ansible playbook..."
        export ANSIBLE_HOST_KEY_CHECKING=False

        # Use the vaulted secret
        ansible-playbook /home/kdsouza/Project/playbook-test.yml --vault-password-file vault_pass.txt -vvvv
      displayName: Run Ansible Playbook
      env: 
        SSH_PASSWORD: $(SSH_PASSWORD)
