trigger:
- main

pool:
  name: 'Default'

stages:
- stage: RunAnsible
  jobs: 
  - job: RunPlaybookOnHosts
    steps:
    - script: |
        echo "Running Ansible playbook..."
        export ANSIBLE_HOST_KEY_CHECKING=False
        sshpass -p "$SSH_PASSWORD" ansible-playbook /home/kdsouza/Project/playbook-test.yml -vvvv
      env: 
        SSH_PASSWORD: $(SSH_PASSWORD)
      displayName: Run Ansible Playbook with sshpass
