trigger:
- main

pool:
  name: 'Default'

parameters:
  - name: hostname
    type: string
    default: "127.0.0.1"
  - name: os
    type: string
    default: "windows"
    
variables:
  - name: ssh_p
    value: $(SSH_PASSWORD)

stages:
# - stage: CreateInventory
  # jobs:
  # - job: WriteToInventory
  #   steps: 
  #   - script: echo "Message ${{ parameters.hostname}}"
  #     displayName: 'Echo api message'

  #   - ${{ if eq(parameters.os, 'windows') }}: # same as below msg
  #     - script: |
  #         echo "[windows]" >> inventory.ini
  #         echo "${{ parameters.hostname }}" >> inventory.ini

  #         echo "[windows:vars]" >> inventory.ini
  #         echo "ansible_user= administrator" >> inventory.ini
  #         echo "ansible_port= 22" >> inventory.ini
  #         echo "ansible_connection= ssh" >> inventory.ini
  #       displayName: 'Generate Windows Ansible Inventory'

  #   - ${{ if eq(parameters.os, 'rhel') }}: #ideally put this into a text file rhel-config or in azure vars
  #     - script: |
  #         echo "[linux]" >> inventory.ini
  #         echo "${{ parameters.hostname }}" >> inventory.ini

  #         echo "[linux:vars]" >> inventory.ini
  #         echo "ansible_user= administrator" >> inventory.ini
  #         echo "ansible_port= 22" >> inventory.ini
  #         echo "ansible_connection= ssh" >> inventory.ini
  #       displayName: 'Generate RHEL Ansible Inventory'


  #   - script: |
  #         cat inventory.ini
  #         pwd
  #     displayName: 'Display Inventory File'

- stage: RunPlaybook
  jobs:
  - job: WriteToInventory
    steps: 
    - script: echo "Message ${{ parameters.hostname}}"
      displayName: 'Echo api message'

    - ${{ if eq(parameters.os, 'windows') }}: # same as below msg
      - script: |
          echo "[windows]" >> inventory.ini
          echo "${{ parameters.hostname }}" >> inventory.ini

          echo "[windows:vars]" >> inventory.ini
          echo "ansible_user= administrator" >> inventory.ini
          echo "ansible_port= 22" >> inventory.ini
          echo "ansible_connection= ssh" >> inventory.ini
        displayName: 'Generate Windows Ansible Inventory'

    - ${{ if eq(parameters.os, 'rhel') }}: #ideally put this into a text file rhel-config or in azure vars
      - script: |
          echo "[linux]" >> inventory.ini
          echo "${{ parameters.hostname }}" >> inventory.ini

          echo "[linux:vars]" >> inventory.ini
          echo "ansible_user= administrator" >> inventory.ini
          echo "ansible_port= 22" >> inventory.ini
          echo "ansible_connection= ssh" >> inventory.ini
        displayName: 'Generate RHEL Ansible Inventory'


    - script: |
          cat inventory.ini
          pwd
      displayName: 'Display Inventory File'
  - job: AnsiblePlaybook
    steps:
    - script: |
        echo " Running Ansible Playbook..."

        # nmap 192.168.122.45 -Pn
        # ping test.com -c 5
        # ssh administrator@test.com

        #Currently, this runs the playbook but not depending on the type of host. I need to change my playbook to run according to host type.
        export ANSIBLE_HOST_KEY_CHECKING=False
        ansible-playbook /home/kdsouza/Project/playbook-test.yml  --e "ansible_ssh_pass=$(SSH_PASSWORD)"
      displayName: Running Playbook


