trigger:
- main

pool:
  name: 'Default'

stages:
- stage: RunAnsible
  jobs: 
  - job: RunPlaybookOnHosts
    steps:
    - script: |
        echo "Creating Ansible Vault File"
        ansible-vault create pass.yml
        ansible-vault rekey
        
        echo "Running Ansible playbook..."
        
        export ANSIBLE_HOST_KEY_CHECKING=False
        echo $(SSH_PASSWORD) | ansible-playbook /home/kdsouza/Project/playbook-test.yml --vault-password-file=/bin/cat -vvvv

        # ansible-playbook /home/kdsouza/Project/playbook-test.yml -vvvv
      env: 
        SSH_PASSWORD: $(SSH_PASSWORD)
      displayName: Run Ansible Playbook
